export const USER_SINGIN_REQUEST = "USER_SINGIN_REQUEST";
export const USER_SINGIN_SUCCESS = "USER_SINGIN_SUCCESS";
export const USER_SINGIN_FAIL = "USER_SINGIN_FAIL";
export const USER_SINGOUT = "USER_SINGOUT";
